// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgjjslugcqroovfscyje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnampzbHVnY3Fyb292ZnNjeWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NzE5OTksImV4cCI6MjA1MTE0Nzk5OX0.dxVXkTj1Pnwvwg4znpQHIBM4tX2OziR5ySFPUFefCU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);